// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A chatbot for answering questions about Sung Jinwoo and the Solo Leveling universe.
 *
 * - soloLevelingChatbot - A function that handles the chatbot interaction.
 * - SoloLevelingChatbotInput - The input type for the soloLevelingChatbot function.
 * - SoloLevelingChatbotOutput - The return type for the soloLevelingChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SoloLevelingChatbotInputSchema = z.object({
  query: z.string().describe('The user query about Sung Jinwoo and the Solo Leveling universe.'),
});
export type SoloLevelingChatbotInput = z.infer<typeof SoloLevelingChatbotInputSchema>;

const SoloLevelingChatbotOutputSchema = z.object({
  response: z.string().describe('The chatbot response to the user query.'),
});
export type SoloLevelingChatbotOutput = z.infer<typeof SoloLevelingChatbotOutputSchema>;

export async function soloLevelingChatbot(input: SoloLevelingChatbotInput): Promise<SoloLevelingChatbotOutput> {
  return soloLevelingChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'soloLevelingChatbotPrompt',
  input: {schema: SoloLevelingChatbotInputSchema},
  output: {schema: SoloLevelingChatbotOutputSchema},
  prompt: `You are a helpful chatbot assistant expert on Solo Leveling. Answer the following question about Sung Jinwoo and the Solo Leveling universe.\n\nQuestion: {{{query}}} `,
});

const soloLevelingChatbotFlow = ai.defineFlow(
  {
    name: 'soloLevelingChatbotFlow',
    inputSchema: SoloLevelingChatbotInputSchema,
    outputSchema: SoloLevelingChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
